### ISSUE TITLE
Saving image outside the output folder is not allowed

### ISSUE THREAD

**Issue by enternalsaga** [lquesada/ComfyUI-Interactive#1]
Hi, can you update the node to allow saving outside of output folder? would you pls provide the option to change output folder and image name?
The error as follow:
```
 ERROR: Saving image outside the output folder is not allowed.
 full_output_folder: H:\NBA_KTS\OneDrive\Stable_Diffusion\SD_image\extras-images\Realistic
         output_dir: H:\NBA_KTS\OneDrive\Stable_Diffusion\SD_image\comfyui-images
         commonpath: H:\NBA_KTS\OneDrive\Stable_Diffusion\SD_image
```
Thank you.

**Comment by lquesada** [comment]
hi! this is not my nodes, this is ComfyUI, for security reasons.

However, you can work it around from linux and mac by creating a symbolic link to your target path and saving it in your output folder. I see you're in Windows though so your only option is to edit folder_paths.py and remove this part:

    if os.path.commonpath((output_dir, os.path.abspath(full_output_folder))) != output_dir:
        err = "**** ERROR: Saving image outside the output folder is not allowed." + \
              "\n full_output_folder: " + os.path.abspath(full_output_folder) + \
              "\n         output_dir: " + output_dir + \
              "\n         commonpath: " + os.path.commonpath((output_dir, os.path.abspath(full_output_folder)))
        logging.error(err)
        raise Exception(err)



That may work
