### ISSUE TITLE
Import Failed in ComfyUI

### ISSUE THREAD

**Issue by jlsidoti** [lquesada/ComfyUI-Interactive#2]
When starting ComfyUI getting IMPORT FAILED message for folder ComfyUI-Interactive.

`[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 17:07:21.782600
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: J:\Data\Packages\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: J:\Data\Packages\ComfyUI
** Log path: J:\Data\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.9 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 32695 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: J:\Data\Packages\ComfyUI\web
[Crystools INFO] Crystools version: 1.20.0
[Crystools INFO] CPU: Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 560.70
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "J:\Data\Packages\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Interactive\__init__.py", line 1, in <module>
    from .comfyui_interactive import InteractiveSelector
  File "J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Interactive\comfyui_interactive.py", line 12, in <module>
    import impact.core as core
ModuleNotFoundError: No module named 'impact'

Cannot import J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Interactive module for custom nodes: No module named 'impact'
Total VRAM 12287 MB, total RAM 32695 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
### ComfyUI Revision: 2851 [94323a26] | Released on '2024-11-22'
J:\Data\Packages\ComfyUI
############################################
J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
['J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naifilters.csv', 'J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naistyles.csv', 'J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naitypes.csv']
############################################
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
J:\Data\Packages\ComfyUI\venv\lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.17). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
[ReActor] - STATUS - Running v0.5.2-a1 in ComfyUI
Torch version: 2.5.1+cu124
J:\Data\Packages\ComfyUI
############################################
J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
['J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naifilters.csv', 'J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naistyles.csv', 'J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naitypes.csv']
############################################
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
J:\Data\Packages\ComfyUI
############################################
J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
['J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naifilters.csv', 'J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naistyles.csv', 'J:\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\CSV\\naitypes.csv']
############################################
Eden_Comfy_Pipelines: WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.

[rgthree-comfy] Loaded 42 exciting nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `J:\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

	"The artist's world is limitless. It can be found anywhere, far from where he lives or a few feet away. It is always on his doorstep." - Paul Strand

Import times for custom nodes:
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\Image-Captioning-in-ComfyUI
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI_NAI-mod
   0.0 seconds (IMPORT FAILED): J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Interactive
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Prompt-Preview
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-NAI-styler
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-IG-Nodes
   0.4 seconds: J:\Data\Packages\ComfyUI\custom_nodes\comfyui-tensorops
   0.5 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.6 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   1.1 seconds: J:\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.2 seconds: J:\Data\Packages\ComfyUI\custom_nodes\comfyui-reactor-node
   1.4 seconds: J:\Data\Packages\ComfyUI\custom_nodes\eden_comfy_pipelines
   2.4 seconds: J:\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
`

**Comment by jlsidoti** [comment]
Installed the custom nodes ComfyUI-Impact-Pack and the problem appears to be resolved.

**Comment by lquesada** [comment]
I just committed an update and the Impact Pack nodes aren't required anymore. Thanks a lot, this was a nice catch!

**Comment by jlsidoti** [comment]
I'm glad it helped in some small way.  Thanks for sharing your work.
